[project]
authors = ["Pedro Pereira"]
entry = "main.sw"
license = "Apache-2.0"
name = "nft-insurance-contract"

[toolchain]
channel = "testnet"

[components]
forc = "0.70.0"
fuel-core = "0.41.9"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.7.0" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.25.0" }
